site_name: Sequence composition virus-host matching project
repo_url: https://github.com/phenolophthaleinum/fastDNA-faiss
repo_name: phenolophthaleinum/fastDNA-faiss
edit_uri: "edit/master/docs/"
plugins:
  - search
  - mkdocstrings:
      watch:
        - utils
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs